export const GET_CAR_TYPE = "GET_CAR_TYPE";
export const GET_CAR_TYPE_SUCCESS = "GET_CAR_TYPE_SUCCESS";
export const GET_CAR_TYPE_FAILURES = "GET_CAR_TYPE_FAILURES";

export const GET_FUEL_TYPE = "GET_FUEL_TYPE";
export const GET_FUEL_TYPE_SUCCESS = "GET_FUEL_TYPE_SUCCESS";
export const GET_FUEL_TYPE_FAILURES = "GET_FUEL_TYPE_FAILURES";

export const GET_VARIENT = "GET_VARIENT";
export const GET_VARIENT_SUCCESS = "GET_VARIENT_SUCCESS";
export const GET_VARIENT_FAILURES = "GET_VARIENT_FAILURES";
